doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(DATABASE_MASTER_URL)%'
        server_version: 5.7.0
        mapping_types:
          enum: string
        replicas:
          replica:
            url: '%env(DATABASE_SLAVE_URL)%'
    types:
      message_type: AppName\Infrastructure\Doctrine\Types\MessageTypeEnum
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Domain/Entity'
        prefix: 'AppName\Domain\Entity'
        alias: App

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.apcu

  framework:
    cache:
      pools:
        doctrine.apcu:
          adapter: cache.adapter.apcu
