# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
  env(APP_SECRET): 'sfkjhaisuyf4ihf4hsiuefzfe'

framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false

  php_errors:
    log: true

when@test:
  framework:
    test: true
