<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Federation\Resolver\Foundation\Query\_EntitiesResolver as Base_EntitiesResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Do not edit it, it will be regenerated.
 * Representation resolver for federated graphql field Query._entities
 */
final class _entitiesResolver extends Base_EntitiesResolver
{}