<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Federation\Resolver\Foundation\Query\_ServiceResolver as Base_ServiceResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Do not edit it, it will be regenerated.
 * Representation resolver for federated graphql field Query._service
 */
final class _serviceResolver extends Base_ServiceResolver
{}