<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\Directive;

use AppName\Application\GraphQL\Context;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use Axtiva\FlexibleGraphql\Resolver\DirectiveResolverInterface;
use GraphQL\Type\Definition\ResolveInfo;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Resolver for executable directive @isAuthenticated
 */
final class IsAuthenticatedDirective implements DirectiveResolverInterface
{
    /**
     * @param callable|ResolverInterface $next
     * @param array|null $directiveArgs
     * @param mixed $rootValue
     * @param array|null $args
     * @param Context $context
     * @param ResolveInfo $info
     * @return mixed
     */
    public function __invoke(callable $next, $directiveArgs, $rootValue, $args, $context, ResolveInfo $info)
    {
        if (empty($context->getUser())) {
            throw new \LogicException();
        }

        return $next($rootValue, $args, $context, $info);
    }
}