<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\UnionResolveType;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\UnionResolveTypeInterface;
use AppName\Application\GraphQL\Model\MessageType;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 */
final class _EntityTypeResolver implements UnionResolveTypeInterface
{
    public function __invoke($model, $context, ResolveInfo $info)
    {
        if (isset($model)) {
            switch (get_class($model)) {
                case MessageType::class:
                    return $info->schema->getType('Message');
            }
        }
        return null;
    }
}