<?php
/**
 * Autogenerated file by axtiva/flexible-graphql-php Do not edit it manually
 */ 
namespace AppName\Application\GraphQL;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\InterfaceType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ListOfType;
use GraphQL\Type\Definition\NonNull;
use Axtiva\FlexibleGraphql\Type\EnumType;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\CustomScalarType;
use GraphQL\Type\Definition\UnionType;
use GraphQL\Type\Definition\Directive;
use GraphQL\Type\Definition\FieldArgument;
use GraphQL\Type\Definition\FieldDefinition;
use GraphQL\Type\Definition\InputObjectField;
use Psr\Container\ContainerInterface;
use GraphQL\Type\Schema;

class TypeRegistry
{
    private ContainerInterface $container;
    
    /**
     * @var array<string, Type>
     */
    private array $types = [];
    
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function getType(string $name): Type
    {
        return $this->types[$name] ??= $this->{$name}();
    }
    
    
            public function Query()
            {
                return new ObjectType([
            'name' => 'Query',
            'description' => NULL,
            'fields' => fn() => ['message' => FieldDefinition::create([
            'name' => 'message',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function($rootValue, $args, $context, $info) {
                        return $this->container->get('AppName\Application\GraphQL\Directive\HasRoleDirective')(
                        (function ($rootValue, $args, $context, $info) {
    $args = new \AppName\Application\GraphQL\ResolverArgs\Query\MessageResolverArgs($args);
    return $this->container->get('AppName\Application\GraphQL\Resolver\Query\MessageResolver')($rootValue, $args, $context, $info);
}), 
                        array (
  'role' => 'translator',
),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => function() { return $this->getType('Message'); },
            'args' => ['id' => [
            'name' => 'id',
            'type' => function() { return Type::nonNull(function() { return Type::id(); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ]),'_service' => FieldDefinition::create([
            'name' => '_service',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    
    return $this->container->get('AppName\Application\GraphQL\Resolver\Query\_serviceResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return Type::nonNull(function() { return $this->getType('_Service'); }); },
            'args' => [],
        ]),'_entities' => FieldDefinition::create([
            'name' => '_entities',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => (function ($rootValue, $args, $context, $info) {
    $args = new \AppName\Application\GraphQL\ResolverArgs\Query\_entitiesResolverArgs($args);
    return $this->container->get('AppName\Application\GraphQL\Resolver\Query\_entitiesResolver')($rootValue, $args, $context, $info);
}),
            'type' => function() { return Type::nonNull(function() { return new ListOfType(function() { return $this->getType('_Entity'); }); }); },
            'args' => ['representations' => [
            'name' => 'representations',
            'type' => function() { return Type::nonNull(function() { return new ListOfType(function() { return Type::nonNull(function() { return $this->getType('_Any'); }); }); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ])],
        ]);
            }
        


            public function Message()
            {
                return new ObjectType([
            'name' => 'Message',
            'description' => NULL,
            'fields' => fn() => ['id' => FieldDefinition::create([
            'name' => 'id',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::id(); }); },
            'args' => [],
        ]),'text' => FieldDefinition::create([
            'name' => 'text',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::string(); },
            'args' => [],
        ]),'dateCreatedAt' => FieldDefinition::create([
            'name' => 'dateCreatedAt',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return $this->getType('DateTime'); },
            'args' => [],
        ]),'dateUpdateAt' => FieldDefinition::create([
            'name' => 'dateUpdateAt',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return $this->getType('DateTime'); },
            'args' => [],
        ])],
        ]);
            }
        


            public function DateTime()
            {
                return new CustomScalarType([
            'name' => 'DateTime',
            'description' => NULL,
            'serialize' => function($value) {return ($this->container->get('AppName\Application\GraphQL\Scalar\DateTimeScalar'))->serialize($value);},
            'parseValue' => function($value) {return ($this->container->get('AppName\Application\GraphQL\Scalar\DateTimeScalar'))->parseValue($value);},
            'parseLiteral' => function($value, $variables) {return ($this->container->get('AppName\Application\GraphQL\Scalar\DateTimeScalar'))->parseLiteral($value, $variables);},
        ]);
            }
        


            public function _Service()
            {
                return new ObjectType([
            'name' => '_Service',
            'description' => NULL,
            'fields' => fn() => ['sdl' => FieldDefinition::create([
            'name' => 'sdl',
            'description' => NULL,
            'deprecationReason' => NULL,
            // No resolver. Default used
            'type' => function() { return Type::nonNull(function() { return Type::string(); }); },
            'args' => [],
        ])],
        ]);
            }
        


            public function _Any()
            {
                return new CustomScalarType([
            'name' => '_Any',
            'description' => NULL,

        ]);
            }
        


            public function _Entity()
            {
                return new UnionType([
            'name' => '_Entity',
            'description' => NULL,
            'types' => function() { return [$this->getType('Message')];},
            'resolveType' => $this->container->get('AppName\Application\GraphQL\UnionResolveType\_EntityTypeResolver'),
        ]);
            }
        


            public function Mutation()
            {
                return new ObjectType([
            'name' => 'Mutation',
            'description' => NULL,
            'fields' => fn() => ['createMessage' => FieldDefinition::create([
            'name' => 'createMessage',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function($rootValue, $args, $context, $info) {
                        return $this->container->get('AppName\Application\GraphQL\Directive\IsAuthenticatedDirective')(
                        (function ($rootValue, $args, $context, $info) {
    $args = new \AppName\Application\GraphQL\ResolverArgs\Mutation\CreateMessageResolverArgs($args);
    return $this->container->get('AppName\Application\GraphQL\Resolver\Mutation\CreateMessageResolver')($rootValue, $args, $context, $info);
}), 
                        array (
),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => function() { return $this->getType('Message'); },
            'args' => ['input' => [
            'name' => 'input',
            'type' => function() { return Type::nonNull(function() { return $this->getType('CreateMessageInput'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ]),'updateMessage' => FieldDefinition::create([
            'name' => 'updateMessage',
            'description' => NULL,
            'deprecationReason' => NULL,
            'resolve' => function($rootValue, $args, $context, $info) {
                        return $this->container->get('AppName\Application\GraphQL\Directive\HasRoleDirective')(
                        (function ($rootValue, $args, $context, $info) {
    $args = new \AppName\Application\GraphQL\ResolverArgs\Mutation\UpdateMessageResolverArgs($args);
    return $this->container->get('AppName\Application\GraphQL\Resolver\Mutation\UpdateMessageResolver')($rootValue, $args, $context, $info);
}), 
                        array (
  'role' => 'marketing',
),
                        $rootValue, $args, $context, $info
                        );
                    },
            'type' => function() { return $this->getType('Message'); },
            'args' => ['input' => [
            'name' => 'input',
            'type' => function() { return Type::nonNull(function() { return $this->getType('UpdateMessageInput'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]],
        ])],
        ]);
            }
        


            public function CreateMessageInput()
            {
                return new InputObjectType([
        'name' => 'CreateMessageInput',
        'description' =>  NULL,
        'fields' => fn() => ['text' => [
            'name' => 'text',
            'description' => NULL,
            'defaultValue' => NULL,
            'type' => Type::nonNull(function() { return Type::string(); }),
        ]],
        ]);
            }
        


            public function UpdateMessageInput()
            {
                return new InputObjectType([
        'name' => 'UpdateMessageInput',
        'description' =>  NULL,
        'fields' => fn() => ['id' => [
            'name' => 'id',
            'description' => NULL,
            'defaultValue' => NULL,
            'type' => Type::nonNull(function() { return Type::id(); }),
        ],'text' => [
            'name' => 'text',
            'description' => NULL,
            'defaultValue' => NULL,
            'type' => Type::nonNull(function() { return Type::string(); }),
        ]],
        ]);
            }
        


            public function link__Import()
            {
                return new CustomScalarType([
            'name' => 'link__Import',
            'description' => NULL,

        ]);
            }
        


            public function FieldSet()
            {
                return new CustomScalarType([
            'name' => 'FieldSet',
            'description' => NULL,

        ]);
            }
        


    public function directive_link()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'link',
            'description' => NULL,
            'isRepeatable' => true,
            'locations' => ['SCHEMA'],
            'args' => [
                [
            'name' => 'url',
            'type' => function() { return Type::string(); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],[
            'name' => 'as',
            'type' => function() { return Type::string(); },
            'defaultValue' => NULL,
            'description' => NULL,
        ],[
            'name' => 'import',
            'type' => function() { return new ListOfType(function() { return $this->getType('link__Import'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_external()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'external',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_requires()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'requires',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'fields',
            'type' => function() { return Type::nonNull(function() { return $this->getType('FieldSet'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_provides()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'provides',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'fields',
            'type' => function() { return Type::nonNull(function() { return $this->getType('FieldSet'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_key()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'key',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [
                [
            'name' => 'fields',
            'type' => function() { return Type::nonNull(function() { return $this->getType('FieldSet'); }); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_extends()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'extends',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['OBJECT','INTERFACE'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_isAuthenticated()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'isAuthenticated',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function directive_hasRole()
    {
        static $directive = null;
        if ($directive === null) {
            $directive = new Directive([
            'name' => 'hasRole',
            'description' => NULL,
            'isRepeatable' => false,
            'locations' => ['FIELD_DEFINITION'],
            'args' => [
                [
            'name' => 'role',
            'type' => function() { return Type::string(); },
            'defaultValue' => NULL,
            'description' => NULL,
        ]
            ],
        ]);
        }
        
        return $directive;
    }
        


    public function getDirectives()
    {
        return [$this->directive_link(),$this->directive_external(),$this->directive_requires(),$this->directive_provides(),$this->directive_key(),$this->directive_extends(),$this->directive_isAuthenticated(),$this->directive_hasRole()];
    }
        

}
