<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\Model;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 */
interface _EntityInterface
{}