<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\Model;

use Axtiva\FlexibleGraphql\Type\InputType;

/**
 * This code is @generated by axtiva/flexible-graphql-php do not edit it
 * PHP representation of graphql type CreateMessageInput
 * @property string $text 
 */
final class CreateMessageInputInputType extends InputType
{
    protected function decorate($name, $value)
    {
        if ($value === null) {
            return null;
        }

        return $value;
    }
}