<?php

declare (strict_types=1);
namespace AppName\Application\GraphQL\Model;

use Axtiva\FlexibleGraphql\Resolver\AutoGenerationInterface;
use DateTimeImmutable;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * if you want to extend it or change, then remove interface AutoGenerationInterface
 * and it will be managed by you, not axtiva/flexible-graphql-php code generator
 * PHP representation of graphql type Message
 */
final class MessageType implements AutoGenerationInterface, _EntityInterface
{
    public string $id;
    public ?string $text = null;
    public ?DateTimeImmutable $dateCreatedAt = null;
    public ?DateTimeImmutable $dateUpdateAt = null;
}